[2024-06-10 21:03:27: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-10 21:03:27: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-10 21:03:27: INFO:common: created directory at: artifacts]
[2024-06-10 21:03:32: INFO:app: <--------Sentiment Model called for prediction-------->]
[2024-06-10 21:03:32: INFO:app: 
Text: Testing the sentiment model prediction response with some random text 
Sentiment Probabilities: 
	{'negative': 0.14376436173915863, 'neutral': 0.6492199301719666, 'positive': 0.207015722990036}
Sentiment: neutral
confidence: 0.6492199301719666 
]
[2024-06-10 21:07:05: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-10 21:13:20: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-10 21:13:20: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-10 21:13:20: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-10 21:13:20: INFO:common: created directory at: artifacts]
[2024-06-10 21:14:47: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-10 21:14:47: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-10 21:14:47: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-10 21:14:47: INFO:common: created directory at: artifacts]
[2024-06-10 21:17:52: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-10 21:17:53: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-10 21:17:53: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-10 21:17:53: INFO:common: created directory at: artifacts]
[2024-06-10 21:17:53: INFO:common: created directory at: artifacts/data_ingestion]
[2024-06-10 21:19:17: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-10 21:19:18: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-10 21:19:18: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-10 21:19:18: INFO:common: created directory at: artifacts]
[2024-06-10 21:19:18: INFO:common: created directory at: artifacts/data_ingestion]
[2024-06-10 21:19:52: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-10 21:19:52: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-10 21:19:52: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-10 21:19:52: INFO:common: created directory at: artifacts]
[2024-06-10 21:19:52: INFO:common: created directory at: artifacts/data_ingestion]
[2024-06-10 21:21:21: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-10 21:21:22: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-10 21:21:22: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-10 21:21:22: INFO:common: created directory at: artifacts]
[2024-06-10 21:21:22: INFO:common: created directory at: artifacts/data_ingestion]
[2024-06-10 21:21:28: INFO:2524217308: Dataset downloaded from kaggle]
[2024-06-10 21:21:28: INFO:2524217308: Error creating arrow dataset]
[2024-06-10 21:31:07: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-10 21:31:07: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-10 21:31:07: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-10 21:31:07: INFO:common: created directory at: artifacts]
[2024-06-10 21:31:07: INFO:common: created directory at: artifacts/data_ingestion]
[2024-06-10 21:32:21: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-10 21:32:22: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-10 21:32:22: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-10 21:32:22: INFO:common: created directory at: artifacts]
[2024-06-10 21:32:22: INFO:common: created directory at: artifacts/data_ingestion]
[2024-06-10 21:32:28: INFO:1185730507: Dataset downloaded from kaggle]
[2024-06-10 21:32:33: INFO:1185730507: Successfully created arrow dataset]
[2024-06-10 21:37:58: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-10 21:37:58: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-10 21:37:58: INFO:common: created directory at: artifacts]
[2024-06-10 21:37:58: INFO:common: created directory at: artifacts/data_validation]
[2024-06-10 21:37:58: INFO:2490338134: Validation status: True]
[2024-06-11 08:25:18: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-11 08:25:19: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 08:25:19: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 08:25:19: INFO:common: created directory at: artifacts]
[2024-06-11 08:25:19: INFO:common: created directory at: artifacts/data_ingestion/sentiment/]
[2024-06-11 08:25:19: WARNING:connectionpool: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027D1502E450>: Failed to resolve 'www.kaggle.com' ([Errno 11001] getaddrinfo failed)")': /api/v1/datasets/download/abhi8923shriv/sentiment-analysis-dataset?datasetVersionNumber=None]
[2024-06-11 08:25:19: WARNING:connectionpool: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027D14E33190>: Failed to resolve 'www.kaggle.com' ([Errno 11001] getaddrinfo failed)")': /api/v1/datasets/download/abhi8923shriv/sentiment-analysis-dataset?datasetVersionNumber=None]
[2024-06-11 08:25:19: WARNING:connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027D1794CF50>: Failed to resolve 'www.kaggle.com' ([Errno 11001] getaddrinfo failed)")': /api/v1/datasets/download/abhi8923shriv/sentiment-analysis-dataset?datasetVersionNumber=None]
[2024-06-11 08:26:07: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-11 08:26:07: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 08:26:07: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 08:26:07: INFO:common: created directory at: artifacts]
[2024-06-11 08:26:07: INFO:common: created directory at: artifacts/data_ingestion/sentiment/]
[2024-06-11 08:26:16: INFO:2524217308: Dataset downloaded from kaggle]
[2024-06-11 08:26:23: INFO:2524217308: Successfully created arrow dataset]
[2024-06-11 08:26:51: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 08:26:51: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 08:26:51: INFO:common: created directory at: artifacts]
[2024-06-11 08:26:51: INFO:common: created directory at: artifacts/data_validation]
[2024-06-11 08:27:15: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 08:27:15: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 08:27:15: INFO:common: created directory at: artifacts]
[2024-06-11 08:27:15: INFO:common: created directory at: artifacts/data_validation]
[2024-06-11 08:27:15: INFO:2989141371: Validation status: True]
[2024-06-11 08:27:46: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-11 08:27:47: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 08:27:47: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 08:27:47: INFO:common: created directory at: artifacts]
[2024-06-11 08:27:47: INFO:3120053097: Error creating dataloader]
[2024-06-11 08:28:12: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-11 08:28:12: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 08:28:12: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 08:28:12: INFO:common: created directory at: artifacts]
[2024-06-11 08:28:12: INFO:common: created directory at: artifacts/data_transformation/sentiment/]
[2024-06-11 08:28:13: INFO:3235233465: Successfully saved train dataloader to artifacts/data_transformation/sentiment/]
[2024-06-11 08:28:13: INFO:3235233465: Successfully saved test dataloader to artifacts/data_transformation/sentiment/]
[2024-06-11 08:28:14: INFO:3235233465: Successfully saved validation dataloader to artifacts/data_transformation/sentiment/]
[2024-06-11 08:30:57: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 08:30:57: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 08:30:57: INFO:common: created directory at: artifacts]
[2024-06-11 08:30:57: INFO:common: created directory at: artifacts/data_validation/sentiment]
[2024-06-11 08:30:57: INFO:2989141371: Validation status: True]
[2024-06-11 08:38:32: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-11 08:38:33: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 08:38:33: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 08:38:33: INFO:common: created directory at: artifacts]
[2024-06-11 08:38:33: INFO:common: created directory at: artifacts/data_ingestion/sentiment/]
[2024-06-11 08:38:42: INFO:1675502547: Dataset downloaded from kaggle]
[2024-06-11 08:38:48: INFO:1675502547: Successfully created arrow dataset]
[2024-06-11 08:39:25: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 08:39:25: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 08:39:25: INFO:common: created directory at: artifacts]
[2024-06-11 08:39:25: INFO:common: created directory at: artifacts/data_validation/sentiment]
[2024-06-11 08:39:25: INFO:2989141371: Validation status: True]
[2024-06-11 08:39:44: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-11 08:39:45: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 08:39:45: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 08:39:45: INFO:common: created directory at: artifacts]
[2024-06-11 08:39:45: INFO:common: created directory at: artifacts/data_transformation/sentiment/]
[2024-06-11 08:39:45: INFO:3235233465: Successfully saved train dataloader to artifacts/data_transformation/sentiment/]
[2024-06-11 08:39:45: INFO:3235233465: Successfully saved test dataloader to artifacts/data_transformation/sentiment/]
[2024-06-11 08:39:46: INFO:3235233465: Successfully saved validation dataloader to artifacts/data_transformation/sentiment/]
[2024-06-11 09:05:50: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-11 09:30:58: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-11 09:31:03: INFO:sentiment_model_trainer: >>>>>> stage: Data Ingestion stage started <<<<<<]
[2024-06-11 09:31:03: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 09:31:03: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 09:31:03: INFO:common: created directory at: artifacts]
[2024-06-11 09:31:03: ERROR:sentiment_model_trainer: 'ConfigurationManager' object has no attribute 'get_data_ingestion_config']
Traceback (most recent call last):
  File "C:\Work\Tasks\Repo\uc_api\sentiment_model_trainer.py", line 23, in <module>
    data_ingestion.main()
  File "C:\Work\Tasks\Repo\uc_api\src\uc_api\pipeline\sentiment\stage_01_data_ingestion.py", line 11, in main
    data_ingestion_config = config.get_data_ingestion_config()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigurationManager' object has no attribute 'get_data_ingestion_config'
[2024-06-11 09:31:56: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-11 09:32:00: INFO:sentiment_model_trainer: >>>>>> stage: Data Ingestion stage started <<<<<<]
[2024-06-11 09:32:00: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 09:32:00: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 09:32:00: INFO:common: created directory at: artifacts]
[2024-06-11 09:32:00: INFO:common: created directory at: artifacts/data_ingestion/sentiment/]
[2024-06-11 09:32:00: INFO:data_ingestion: File already exists of size: ~ 55755 KB]
[2024-06-11 09:32:05: INFO:data_ingestion: Successfully created arrow dataset]
[2024-06-11 09:32:05: INFO:sentiment_model_trainer: >>>>>> stage: Data Ingestion stage completed <<<<<<

x===============================x]
[2024-06-11 09:32:05: INFO:sentiment_model_trainer: >>>>>> stage: Data Validation stage started <<<<<<]
[2024-06-11 09:32:05: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 09:32:05: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 09:32:05: INFO:common: created directory at: artifacts]
[2024-06-11 09:32:05: ERROR:sentiment_model_trainer: "'ConfigBox' object has no attribute 'data_validation'"]
Traceback (most recent call last):
  File "box\\box.py", line 592, in box.box.Box.__getitem__
KeyError: 'data_validation'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\box.py", line 631, in box.box.Box.__getattr__
  File "box\\box.py", line 619, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'data_validation'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 633, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'data_validation'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\config_box.py", line 29, in box.config_box.ConfigBox.__getattr__
  File "box\\box.py", line 647, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'data_validation'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 592, in box.box.Box.__getitem__
KeyError: 'data_validation'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\box.py", line 631, in box.box.Box.__getattr__
  File "box\\box.py", line 619, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'data_validation'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 633, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'data_validation'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Work\Tasks\Repo\uc_api\sentiment_model_trainer.py", line 34, in <module>
    data_validation.main()
  File "C:\Work\Tasks\Repo\uc_api\src\uc_api\pipeline\sentiment\stage_02_data_validation.py", line 13, in main
    data_validation_config = config.get_sentiment_data_validation_config()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\Tasks\Repo\uc_api\src\uc_api\config\configuration.py", line 60, in get_sentiment_data_validation_config
    config = self.config.data_validation
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "box\\config_box.py", line 31, in box.config_box.ConfigBox.__getattr__
  File "box\\box.py", line 647, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'data_validation'"
[2024-06-11 09:34:11: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-11 09:34:15: INFO:sentiment_model_trainer: >>>>>> stage: Data Ingestion stage started <<<<<<]
[2024-06-11 09:34:15: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 09:34:15: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 09:34:15: INFO:common: created directory at: artifacts]
[2024-06-11 09:34:15: INFO:common: created directory at: artifacts/data_ingestion/sentiment/]
[2024-06-11 09:34:15: INFO:data_ingestion: File already exists of size: ~ 55755 KB]
[2024-06-11 09:34:19: INFO:data_ingestion: Successfully created arrow dataset]
[2024-06-11 09:34:19: INFO:sentiment_model_trainer: >>>>>> stage: Data Ingestion stage completed <<<<<<

x===============================x]
[2024-06-11 09:34:19: INFO:sentiment_model_trainer: >>>>>> stage: Data Validation stage started <<<<<<]
[2024-06-11 09:34:19: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 09:34:19: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 09:34:19: INFO:common: created directory at: artifacts]
[2024-06-11 09:34:19: INFO:common: created directory at: artifacts/data_validation/sentiment]
[2024-06-11 09:34:19: INFO:data_validation: Validation status: True]
[2024-06-11 09:34:19: INFO:sentiment_model_trainer: >>>>>> stage: Data Validation stage completed <<<<<<

x===============================x]
[2024-06-11 09:34:19: INFO:sentiment_model_trainer: >>>>>> stage: Sentiment Data Transformation stage started <<<<<<]
[2024-06-11 09:34:19: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 09:34:19: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 09:34:19: INFO:common: created directory at: artifacts]
[2024-06-11 09:34:19: INFO:common: created directory at: artifacts/data_transformation/sentiment/]
[2024-06-11 09:34:20: INFO:data_transformation: Successfully saved train dataloader to artifacts/data_transformation/sentiment/]
[2024-06-11 09:34:21: INFO:data_transformation: Successfully saved test dataloader to artifacts/data_transformation/sentiment/]
[2024-06-11 09:34:21: INFO:data_transformation: Successfully saved validation dataloader to artifacts/data_transformation/sentiment/]
[2024-06-11 09:34:21: INFO:sentiment_model_trainer: >>>>>> stage: Sentiment Data Transformation stage completed <<<<<<

x===============================x]
[2024-06-11 09:34:21: INFO:sentiment_model_trainer: >>>>>> stage: Model Trainer & Evaluation stage started <<<<<<]
[2024-06-11 09:34:21: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 09:34:21: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 09:34:21: INFO:common: created directory at: artifacts]
[2024-06-11 09:34:21: INFO:common: created directory at: artifacts/model_trainer/sentiment/model]
[2024-06-11 09:34:55: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-11 09:34:59: INFO:sentiment_model_trainer: >>>>>> stage: Data Ingestion stage started <<<<<<]
[2024-06-11 09:34:59: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 09:34:59: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 09:34:59: INFO:common: created directory at: artifacts]
[2024-06-11 09:34:59: INFO:common: created directory at: artifacts/data_ingestion/sentiment/]
[2024-06-11 09:34:59: INFO:data_ingestion: File already exists of size: ~ 55755 KB]
[2024-06-11 09:35:03: INFO:data_ingestion: Successfully created arrow dataset]
[2024-06-11 09:35:03: INFO:sentiment_model_trainer: >>>>>> stage: Data Ingestion stage completed <<<<<<

x===============================x]
[2024-06-11 09:35:03: INFO:sentiment_model_trainer: >>>>>> stage: Data Validation stage started <<<<<<]
[2024-06-11 09:35:03: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 09:35:03: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 09:35:03: INFO:common: created directory at: artifacts]
[2024-06-11 09:35:03: INFO:common: created directory at: artifacts/data_validation/sentiment]
[2024-06-11 09:35:03: INFO:data_validation: Validation status: True]
[2024-06-11 09:35:03: INFO:sentiment_model_trainer: >>>>>> stage: Data Validation stage completed <<<<<<

x===============================x]
[2024-06-11 09:35:03: INFO:sentiment_model_trainer: >>>>>> stage: Sentiment Data Transformation stage started <<<<<<]
[2024-06-11 09:35:03: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 09:35:03: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 09:35:03: INFO:common: created directory at: artifacts]
[2024-06-11 09:35:03: INFO:common: created directory at: artifacts/data_transformation/sentiment/]
[2024-06-11 09:35:03: INFO:data_transformation: Successfully saved train dataloader to artifacts/data_transformation/sentiment/]
[2024-06-11 09:35:04: INFO:data_transformation: Successfully saved test dataloader to artifacts/data_transformation/sentiment/]
[2024-06-11 09:35:05: INFO:data_transformation: Successfully saved validation dataloader to artifacts/data_transformation/sentiment/]
[2024-06-11 09:35:05: INFO:sentiment_model_trainer: >>>>>> stage: Sentiment Data Transformation stage completed <<<<<<

x===============================x]
[2024-06-11 09:35:05: INFO:sentiment_model_trainer: >>>>>> stage: Model Trainer & Evaluation stage started <<<<<<]
[2024-06-11 09:35:05: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 09:35:05: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 09:35:05: INFO:common: created directory at: artifacts]
[2024-06-11 09:35:05: INFO:common: created directory at: artifacts/model_trainer/sentiment/model]
[2024-06-11 09:38:45: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-11 09:38:48: INFO:sentiment_model_trainer: >>>>>> stage: Data Ingestion stage started <<<<<<]
[2024-06-11 09:38:48: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 09:38:48: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 09:38:48: INFO:common: created directory at: artifacts]
[2024-06-11 09:38:48: INFO:common: created directory at: artifacts/sentiment/data_ingestion/]
[2024-06-11 09:38:56: INFO:data_ingestion: Dataset downloaded from kaggle]
[2024-06-11 09:39:01: INFO:data_ingestion: Successfully created arrow dataset]
[2024-06-11 09:39:01: INFO:sentiment_model_trainer: >>>>>> stage: Data Ingestion stage completed <<<<<<

x===============================x]
[2024-06-11 09:39:01: INFO:sentiment_model_trainer: >>>>>> stage: Data Validation stage started <<<<<<]
[2024-06-11 09:39:01: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 09:39:01: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 09:39:01: INFO:common: created directory at: artifacts]
[2024-06-11 09:39:01: INFO:common: created directory at: artifacts/sentiment/data_validation/]
[2024-06-11 09:39:01: ERROR:sentiment_model_trainer: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\sentiment\\processed']
Traceback (most recent call last):
  File "C:\Work\Tasks\Repo\uc_api\sentiment_model_trainer.py", line 34, in <module>
    data_validation.main()
  File "C:\Work\Tasks\Repo\uc_api\src\uc_api\pipeline\sentiment\stage_02_data_validation.py", line 15, in main
    data_validation.validate_all_files_exist()
  File "C:\Work\Tasks\Repo\uc_api\src\uc_api\components\sentiment\data_validation.py", line 25, in validate_all_files_exist
    raise e
  File "C:\Work\Tasks\Repo\uc_api\src\uc_api\components\sentiment\data_validation.py", line 15, in validate_all_files_exist
    dataset_dirs = [f.name for f in os.scandir(path) if f.is_dir()]
                                    ^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\sentiment\\processed'
[2024-06-11 09:39:43: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-11 09:39:47: INFO:sentiment_model_trainer: >>>>>> stage: Data Ingestion stage started <<<<<<]
[2024-06-11 09:39:47: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 09:39:47: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 09:39:47: INFO:common: created directory at: artifacts]
[2024-06-11 09:39:48: INFO:common: created directory at: artifacts/sentiment/data_ingestion/]
[2024-06-11 09:39:55: INFO:data_ingestion: Dataset downloaded from kaggle]
[2024-06-11 09:40:00: INFO:data_ingestion: Successfully created arrow dataset]
[2024-06-11 09:40:00: INFO:sentiment_model_trainer: >>>>>> stage: Data Ingestion stage completed <<<<<<

x===============================x]
[2024-06-11 09:40:00: INFO:sentiment_model_trainer: >>>>>> stage: Data Validation stage started <<<<<<]
[2024-06-11 09:40:00: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 09:40:00: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 09:40:00: INFO:common: created directory at: artifacts]
[2024-06-11 09:40:00: INFO:common: created directory at: artifacts/sentiment/data_validation/]
[2024-06-11 09:40:00: INFO:data_validation: Validation status: True]
[2024-06-11 09:40:00: INFO:sentiment_model_trainer: >>>>>> stage: Data Validation stage completed <<<<<<

x===============================x]
[2024-06-11 09:40:00: INFO:sentiment_model_trainer: >>>>>> stage: Sentiment Data Transformation stage started <<<<<<]
[2024-06-11 09:40:00: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 09:40:00: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 09:40:00: INFO:common: created directory at: artifacts]
[2024-06-11 09:40:00: INFO:common: created directory at: artifacts/sentiment/data_transformation/]
[2024-06-11 09:40:01: INFO:data_transformation: Successfully saved train dataloader to artifacts/sentiment/data_transformation/]
[2024-06-11 09:40:02: INFO:data_transformation: Successfully saved test dataloader to artifacts/sentiment/data_transformation/]
[2024-06-11 09:40:02: INFO:data_transformation: Successfully saved validation dataloader to artifacts/sentiment/data_transformation/]
[2024-06-11 09:40:02: INFO:sentiment_model_trainer: >>>>>> stage: Sentiment Data Transformation stage completed <<<<<<

x===============================x]
[2024-06-11 09:40:02: INFO:sentiment_model_trainer: >>>>>> stage: Model Trainer & Evaluation stage started <<<<<<]
[2024-06-11 09:40:02: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 09:40:02: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 09:40:02: INFO:common: created directory at: artifacts]
[2024-06-11 09:40:02: INFO:common: created directory at: artifacts/sentiment/model_trainer/model]
[2024-06-11 10:12:52: INFO:sentiment_model_trainer: >>>>>> stage: Model Trainer & Evaluation stage completed <<<<<<

x===============================x]
[2024-06-11 10:12:52: INFO:sentiment_model_trainer: >>>>>> stage: Model Testing stage started <<<<<<]
[2024-06-11 10:12:52: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 10:12:52: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 10:12:52: INFO:common: created directory at: artifacts]
[2024-06-11 10:14:29: INFO:sentiment_model_trainer: >>>>>> stage: Model Testing stage completed <<<<<<

x===============================x]
[2024-06-11 10:36:06: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-11 10:36:07: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 10:36:07: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 10:36:07: INFO:common: created directory at: artifacts]
[2024-06-11 10:36:42: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-11 10:36:42: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 10:36:42: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 10:36:42: INFO:common: created directory at: artifacts]
[2024-06-11 10:36:42: INFO:common: created directory at: artifacts/sentiment/data_ingestion/]
[2024-06-11 10:36:42: INFO:2879523836: File already exists of size: ~ 55755 KB]
[2024-06-11 10:36:49: INFO:2879523836: Successfully created arrow dataset]
[2024-06-11 10:37:12: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 10:37:12: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 10:37:12: INFO:common: created directory at: artifacts]
[2024-06-11 10:37:12: INFO:common: created directory at: artifacts/sentiment/data_validation/]
[2024-06-11 10:37:12: INFO:3787504872: Validation status: True]
[2024-06-11 10:37:40: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-11 10:37:40: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 10:37:40: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 10:37:40: INFO:common: created directory at: artifacts]
[2024-06-11 10:37:40: INFO:common: created directory at: artifacts/sentiment/data_transformation/]
[2024-06-11 10:37:41: INFO:3967033082: Successfully saved train dataloader to artifacts/sentiment/data_transformation/]
[2024-06-11 10:37:41: INFO:3967033082: Successfully saved test dataloader to artifacts/sentiment/data_transformation/]
[2024-06-11 10:37:42: INFO:3967033082: Successfully saved validation dataloader to artifacts/sentiment/data_transformation/]
[2024-06-11 10:38:13: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-11 10:38:13: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 10:38:13: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 10:38:13: INFO:common: created directory at: artifacts]
[2024-06-11 10:39:47: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-11 10:39:47: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 10:39:47: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 10:39:47: INFO:common: created directory at: artifacts]
[2024-06-11 10:40:19: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-11 10:40:19: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 10:40:19: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 10:40:19: INFO:common: created directory at: artifacts]
[2024-06-11 10:40:19: INFO:common: created directory at: artifacts/summarizer/data_ingestion]
[2024-06-11 10:40:24: INFO:1651794886: Dataset downloaded from kaggle]
[2024-06-11 10:40:26: INFO:1651794886: Successfully created arrow dataset]
[2024-06-11 10:40:54: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 10:40:54: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 10:40:54: INFO:common: created directory at: artifacts]
[2024-06-11 10:41:15: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 10:41:15: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 10:41:15: INFO:common: created directory at: artifacts]
[2024-06-11 10:41:15: INFO:common: created directory at: artifacts/summarizer/data_validation/]
[2024-06-11 10:41:15: INFO:609173560: Validation status: True]
[2024-06-11 13:11:41: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 13:11:41: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 13:11:41: INFO:common: created directory at: artifacts]
[2024-06-11 13:12:15: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 13:12:15: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 13:12:15: INFO:common: created directory at: artifacts]
[2024-06-11 13:12:45: INFO:app: <--------Sentiment Model called for prediction-------->]
[2024-06-11 13:12:45: INFO:app: 
Text: Testing the model response with some random text 
Sentiment Probabilities: 
	{'negative': 0.20950724184513092, 'neutral': 0.6376392841339111, 'positive': 0.15285354852676392}
Sentiment: neutral
confidence: 0.6376392841339111 
]
[2024-06-11 13:28:26: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-11 13:29:30: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-11 13:29:30: INFO:summarizer_model_trainer: >>>>>> stage: Data Ingestion stage started <<<<<<]
[2024-06-11 13:29:30: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 13:29:30: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 13:29:30: INFO:common: created directory at: artifacts]
[2024-06-11 13:29:30: INFO:common: created directory at: artifacts/sentiment/data_ingestion/]
[2024-06-11 13:29:30: INFO:data_ingestion: File already exists of size: ~ 55755 KB]
[2024-06-11 13:29:37: INFO:data_ingestion: Successfully created arrow dataset]
[2024-06-11 13:29:37: INFO:summarizer_model_trainer: >>>>>> stage: Data Ingestion stage completed <<<<<<

x===============================x]
[2024-06-11 13:29:37: INFO:summarizer_model_trainer: >>>>>> stage: Data Validation stage started <<<<<<]
[2024-06-11 13:29:37: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 13:29:37: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 13:29:37: INFO:common: created directory at: artifacts]
[2024-06-11 13:29:37: INFO:common: created directory at: artifacts/sentiment/data_validation/]
[2024-06-11 13:29:37: ERROR:summarizer_model_trainer: [WinError 3] The system cannot find the path specified: 'artifacts\\summarizer\\data_ingestion\\processed']
Traceback (most recent call last):
  File "C:\Work\Tasks\Repo\uc_api\summarizer_model_trainer.py", line 34, in <module>
    data_validation.main()
  File "C:\Work\Tasks\Repo\uc_api\src\uc_api\pipeline\summarizer\stage_02_data_validation.py", line 15, in main
    data_validation.validate_all_files_exist()
  File "C:\Work\Tasks\Repo\uc_api\src\uc_api\components\summarizer\data_validation.py", line 25, in validate_all_files_exist
    raise e
  File "C:\Work\Tasks\Repo\uc_api\src\uc_api\components\summarizer\data_validation.py", line 15, in validate_all_files_exist
    dataset_dirs = [f.name for f in os.scandir(path) if f.is_dir()]
                                    ^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\summarizer\\data_ingestion\\processed'
[2024-06-11 14:09:02: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-11 14:09:03: INFO:summarizer_model_trainer: >>>>>> stage: Data Ingestion stage started <<<<<<]
[2024-06-11 14:09:03: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 14:09:03: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 14:09:03: INFO:common: created directory at: artifacts]
[2024-06-11 14:09:03: INFO:common: created directory at: artifacts/sentiment/data_ingestion/]
[2024-06-11 14:09:03: INFO:data_ingestion: File already exists of size: ~ 55755 KB]
[2024-06-11 14:09:04: INFO:data_ingestion: Error creating arrow dataset]
[2024-06-11 14:09:04: ERROR:summarizer_model_trainer: list index out of range]
Traceback (most recent call last):
  File "C:\Work\Tasks\Repo\uc_api\summarizer_model_trainer.py", line 23, in <module>
    data_ingestion.main()
  File "C:\Work\Tasks\Repo\uc_api\src\uc_api\pipeline\summarizer\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.convert_csv_to_train_and_test_datasets()
  File "C:\Work\Tasks\Repo\uc_api\src\uc_api\components\summarizer\data_ingestion.py", line 100, in convert_csv_to_train_and_test_datasets
    raise e
  File "C:\Work\Tasks\Repo\uc_api\src\uc_api\components\summarizer\data_ingestion.py", line 65, in convert_csv_to_train_and_test_datasets
    selected_file = [
                    ^
IndexError: list index out of range
[2024-06-11 14:10:49: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-11 14:10:49: INFO:summarizer_model_trainer: >>>>>> stage: Data Ingestion stage started <<<<<<]
[2024-06-11 14:10:49: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 14:10:49: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 14:10:49: INFO:common: created directory at: artifacts]
[2024-06-11 14:10:49: INFO:common: created directory at: artifacts/sentiment/data_ingestion/]
[2024-06-11 14:10:49: INFO:data_ingestion: File already exists of size: ~ 55755 KB]
[2024-06-11 14:10:50: INFO:data_ingestion: Error creating arrow dataset]
[2024-06-11 14:10:50: ERROR:summarizer_model_trainer: list index out of range]
Traceback (most recent call last):
  File "C:\Work\Tasks\Repo\uc_api\summarizer_model_trainer.py", line 23, in <module>
    data_ingestion.main()
  File "C:\Work\Tasks\Repo\uc_api\src\uc_api\pipeline\summarizer\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.convert_csv_to_train_and_test_datasets()
  File "C:\Work\Tasks\Repo\uc_api\src\uc_api\components\summarizer\data_ingestion.py", line 100, in convert_csv_to_train_and_test_datasets
    raise e
  File "C:\Work\Tasks\Repo\uc_api\src\uc_api\components\summarizer\data_ingestion.py", line 65, in convert_csv_to_train_and_test_datasets
    selected_file = [
                    ^
IndexError: list index out of range
[2024-06-11 14:11:06: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-11 14:11:07: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 14:11:07: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 14:11:07: INFO:common: created directory at: artifacts]
[2024-06-11 14:11:07: INFO:common: created directory at: artifacts/summarizer/data_ingestion]
[2024-06-11 14:11:12: INFO:1651794886: Dataset downloaded from kaggle]
[2024-06-11 14:11:16: INFO:1651794886: Successfully created arrow dataset]
[2024-06-11 14:12:19: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-11 14:12:19: INFO:summarizer_model_trainer: >>>>>> stage: Data Ingestion stage started <<<<<<]
[2024-06-11 14:12:19: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 14:12:19: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 14:12:19: INFO:common: created directory at: artifacts]
[2024-06-11 14:12:19: INFO:common: created directory at: artifacts/sentiment/data_ingestion/]
[2024-06-11 14:12:19: INFO:data_ingestion: File already exists of size: ~ 55755 KB]
[2024-06-11 14:12:20: INFO:data_ingestion: Error creating arrow dataset]
[2024-06-11 14:12:20: ERROR:summarizer_model_trainer: list index out of range]
Traceback (most recent call last):
  File "C:\Work\Tasks\Repo\uc_api\summarizer_model_trainer.py", line 23, in <module>
    data_ingestion.main()
  File "C:\Work\Tasks\Repo\uc_api\src\uc_api\pipeline\summarizer\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.convert_csv_to_train_and_test_datasets()
  File "C:\Work\Tasks\Repo\uc_api\src\uc_api\components\summarizer\data_ingestion.py", line 100, in convert_csv_to_train_and_test_datasets
    raise e
  File "C:\Work\Tasks\Repo\uc_api\src\uc_api\components\summarizer\data_ingestion.py", line 65, in convert_csv_to_train_and_test_datasets
    selected_file = [
                    ^
IndexError: list index out of range
[2024-06-11 14:12:39: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-11 14:12:39: INFO:summarizer_model_trainer: >>>>>> stage: Data Ingestion stage started <<<<<<]
[2024-06-11 14:12:39: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 14:12:39: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 14:12:39: INFO:common: created directory at: artifacts]
[2024-06-11 14:12:39: INFO:common: created directory at: artifacts/sentiment/data_ingestion/]
[2024-06-11 14:12:39: INFO:data_ingestion: File already exists of size: ~ 55755 KB]
[2024-06-11 14:12:40: INFO:data_ingestion: Error creating arrow dataset]
[2024-06-11 14:12:40: ERROR:summarizer_model_trainer: list index out of range]
Traceback (most recent call last):
  File "C:\Work\Tasks\Repo\uc_api\summarizer_model_trainer.py", line 23, in <module>
    data_ingestion.main()
  File "C:\Work\Tasks\Repo\uc_api\src\uc_api\pipeline\summarizer\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.convert_csv_to_train_and_test_datasets()
  File "C:\Work\Tasks\Repo\uc_api\src\uc_api\components\summarizer\data_ingestion.py", line 101, in convert_csv_to_train_and_test_datasets
    raise e
  File "C:\Work\Tasks\Repo\uc_api\src\uc_api\components\summarizer\data_ingestion.py", line 65, in convert_csv_to_train_and_test_datasets
    selected_file = [
                    ^
IndexError: list index out of range
[2024-06-11 14:14:09: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-11 14:14:10: INFO:summarizer_model_trainer: >>>>>> stage: Data Ingestion stage started <<<<<<]
[2024-06-11 14:14:10: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 14:14:10: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 14:14:10: INFO:common: created directory at: artifacts]
[2024-06-11 14:14:10: INFO:common: created directory at: artifacts/sentiment/data_ingestion/]
[2024-06-11 14:14:10: INFO:data_ingestion: File already exists of size: ~ 55755 KB]
[2024-06-11 14:14:10: INFO:data_ingestion: Error creating arrow dataset]
[2024-06-11 14:14:10: ERROR:summarizer_model_trainer: list index out of range]
Traceback (most recent call last):
  File "C:\Work\Tasks\Repo\uc_api\summarizer_model_trainer.py", line 23, in <module>
    data_ingestion.main()
  File "C:\Work\Tasks\Repo\uc_api\src\uc_api\pipeline\summarizer\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.convert_csv_to_train_and_test_datasets()
  File "C:\Work\Tasks\Repo\uc_api\src\uc_api\components\summarizer\data_ingestion.py", line 98, in convert_csv_to_train_and_test_datasets
    raise e
  File "C:\Work\Tasks\Repo\uc_api\src\uc_api\components\summarizer\data_ingestion.py", line 63, in convert_csv_to_train_and_test_datasets
    selected_file = [
                    ^
IndexError: list index out of range
[2024-06-11 14:19:26: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-11 14:19:27: INFO:summarizer_model_trainer: >>>>>> stage: Data Ingestion stage started <<<<<<]
[2024-06-11 14:19:27: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 14:19:27: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 14:19:27: INFO:common: created directory at: artifacts]
[2024-06-11 14:19:27: INFO:common: created directory at: artifacts/summarizer/data_ingestion]
[2024-06-11 14:19:31: INFO:data_ingestion: Dataset downloaded from kaggle]
[2024-06-11 14:19:35: INFO:data_ingestion: Successfully created arrow dataset]
[2024-06-11 14:19:35: INFO:summarizer_model_trainer: >>>>>> stage: Data Ingestion stage completed <<<<<<

x===============================x]
[2024-06-11 14:19:35: INFO:summarizer_model_trainer: >>>>>> stage: Data Validation stage started <<<<<<]
[2024-06-11 14:19:35: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 14:19:35: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 14:19:35: INFO:common: created directory at: artifacts]
[2024-06-11 14:19:35: INFO:common: created directory at: artifacts/sentiment/data_validation/]
[2024-06-11 14:19:35: INFO:data_validation: Validation status: True]
[2024-06-11 14:19:35: INFO:summarizer_model_trainer: >>>>>> stage: Data Validation stage completed <<<<<<

x===============================x]
[2024-06-11 14:20:20: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-11 14:20:20: INFO:summarizer_model_trainer: >>>>>> stage: Data Ingestion stage started <<<<<<]
[2024-06-11 14:20:20: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 14:20:20: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 14:20:20: INFO:common: created directory at: artifacts]
[2024-06-11 14:20:20: INFO:common: created directory at: artifacts/summarizer/data_ingestion]
[2024-06-11 14:20:20: INFO:data_ingestion: File already exists of size: ~ 20233 KB]
[2024-06-11 14:20:22: INFO:data_ingestion: Successfully created arrow dataset]
[2024-06-11 14:20:22: INFO:summarizer_model_trainer: >>>>>> stage: Data Ingestion stage completed <<<<<<

x===============================x]
[2024-06-11 14:20:22: INFO:summarizer_model_trainer: >>>>>> stage: Data Validation stage started <<<<<<]
[2024-06-11 14:20:22: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 14:20:22: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 14:20:22: INFO:common: created directory at: artifacts]
[2024-06-11 14:20:22: INFO:common: created directory at: artifacts/summarizer/data_validation/]
[2024-06-11 14:20:22: INFO:data_validation: Validation status: True]
[2024-06-11 14:20:22: INFO:summarizer_model_trainer: >>>>>> stage: Data Validation stage completed <<<<<<

x===============================x]
[2024-06-11 14:33:05: INFO:config: PyTorch version 2.3.1 available.]
[2024-06-11 14:33:07: INFO:common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 14:33:07: INFO:common: yaml file: params.yaml loaded successfully]
[2024-06-11 14:33:07: INFO:common: created directory at: artifacts]
[2024-06-11 14:33:07: INFO:common: created directory at: artifacts/summarizer/data_ingestion]
[2024-06-11 14:33:07: INFO:1651794886: File already exists of size: ~ 20233 KB]
[2024-06-11 14:33:11: INFO:1651794886: Successfully created arrow dataset]
